# Generated by Django 5.2.3 on 2025-06-24 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_notification_reviewcomment_reviewinteraction_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='reviewinteraction',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='reviewinteraction',
            name='review',
        ),
        migrations.RemoveField(
            model_name='reviewinteraction',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='ReviewInteraction',
        ),
    ]
